pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "Kinescope SDK Demo"
include ':app'
include ':kotlin-kinescope-player'
include ':kotlin-kinescope-player-ui'
include ':kotlin-kinescope-shorts'
project(':kotlin-kinescope-shorts').projectDir = file('kotlin-kinescope-shorts/library')